apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: ${NAME_SPACE}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-rest-api
  template:
    metadata:
      labels:
        app: hello-world-rest-api
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/engaged-mariner-440619-n5/my-app-ms-repository/${IMAGE_NAME}
        name: hello-world-rest-api
