apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: ${NAME_SPACE}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8000
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer